(function ($) {
	"use strict";
	var nav = $('nav');
	var navHeight = nav.outerHeight();

	$('.navbar-toggler').on('click', function () {
		if (!$('#mainNav').hasClass('navbar-reduce')) {
			$('#mainNav').addClass('navbar-reduce');
		}
	})

	// Preloader
	$(window).on('load', function () {
		if ($('#preloader').length) {
			$('#preloader').delay(100).fadeOut('slow', function () {
				$(this).remove();
			});
		}
	});

	// Back to top button
	$(window).scroll(function () {
		if ($(this).scrollTop() > 100) {
			$('.back-to-top').fadeIn('slow');
		} else {
			$('.back-to-top').fadeOut('slow');
		}
	});
	$('.back-to-top').click(function () {
		$('html, body').animate({ scrollTop: 0 }, 1500, 'easeInOutExpo');
		return false;
	});

	/*--/ Star ScrollTop /--*/
	$('.scrolltop-mf').on("click", function () {
		$('html, body').animate({
			scrollTop: 0
		}, 1000);
	});

	/*--/ Star Counter /--*/
	$('.counter').counterUp({
		delay: 15,
		time: 2000
	});

	/*--/ Star Scrolling nav /--*/
	$('a.js-scroll[href*="#"]:not([href="#"])').on("click", function () {
		if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
			var target = $(this.hash);
			target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
			if (target.length) {
				$('html, body').animate({
					scrollTop: (target.offset().top - navHeight + 5)
				}, 1000, "easeInOutExpo");
				return false;
			}
		}
	});

	// Closes responsive menu when a scroll trigger link is clicked
	$('.js-scroll').on("click", function () {
		$('.navbar-collapse').collapse('hide');
	});

	// Activate scrollspy to add active class to navbar items on scroll
	$('body').scrollspy({
		target: '#mainNav',
		offset: navHeight
	});
	/*--/ End Scrolling nav /--*/

	/*--/ Navbar Menu Reduce /--*/
	$(window).trigger('scroll');
	$(window).on('scroll', function () {
		var pixels = 50;
		var top = 1200;
		if ($(window).scrollTop() > pixels) {
			$('.navbar-expand-md').addClass('navbar-reduce');
			$('.navbar-expand-md').removeClass('navbar-trans');
		} else {
			$('.navbar-expand-md').addClass('navbar-trans');
			$('.navbar-expand-md').removeClass('navbar-reduce');
		}
		if ($(window).scrollTop() > top) {
			$('.scrolltop-mf').fadeIn(1000, "easeInOutExpo");
		} else {
			$('.scrolltop-mf').fadeOut(1000, "easeInOutExpo");
		}
	});

	/*--/ Star Typed /--*/
	if ($('.text-slider').length == 1) {
		var typed_strings = $('.text-slider-items').text();
		var typed = new Typed('.text-slider', {
			strings: typed_strings.split(','),
			typeSpeed: 80,
			loop: true,
			backDelay: 1100,
			backSpeed: 30
		});
	}

	/*--/ Testimonials owl /--*/
	$('#testimonial-mf').owlCarousel({
		margin: 20,
		autoplay: true,
		autoplayTimeout: 4000,
		autoplayHoverPause: true,
		responsive: {
			0: {
				items: 1,
			}
		}
	});

})(jQuery);





var services = [
	{
		title: "Computerized system validation (CSV) ",
		body: "Computerized system validation (CSV) CSV is the process of documenting that a computer system meets a set of defined system requirements. Validation of computer systems to ensure accuracy, reliability, consistent intended performance, and the ability to discern invalid or altered records is a critical requirement of electronic record compliance, as described in the FDA 21 CFR 11.10 and EMA Annex 11, Section 4."
	}, {
		title: "Spreadsheet validation records",
		body: "Spreadsheet validation records generated by the calculations are electronic records and must therefore comply with EU’s Annex 11 and FDA's 21 CFR Part 11. In-house developed software (Spreadsheet) might even be a GAMP software category 5 application. The GAMP software category defines the extend of activities required to validate your spreadsheet. As part of spreadsheet validation services like spreadsheet development, protocol preparation and excel challenging will be offered."
	}, {
		title: "Computer Software Gap assessments",
		body: "Computer Software Gap assessments the aim of GAP analysis in Computer System Validation is to identify the gap between company’s existing procedures, practices and policies with respect to relevant regulatory guidelines and compliance standards."
	}, {
		title: "Data Integrity Auditing Services",
		body: "Data Integrity Auditing Services new data integrity guidance calls	for enforcing stricter policies	for documentation review.The new FDA data integrity draft guidance proposes that the review of audit trails be mandatory and suggests several steps to complete the review.The process that the FDA recommends consists of determining the scope of the problem,	implementing a corrective action plan.The FDA also encourages hiring a third party auditor to serve as an unbiased reviewer.Advance GxP Solutions can serve as a third party auditor to help prepare you	for your FDA audits."
	}, {
		title: "Annual maintenance contract and Calibrations services",
		body: "Annual maintenance contract and Calibrations services Our engineer visit includes a set of predesigned maintenance actions, which are aimed at enhancing instrument operations, smooth functioning and increasing the life of your testing machine. Our engineers are authorized to access all official spare parts and tools, plus latest documentation - keeping a check on your equipment and its performance.	The biggest advantage of enrolling for our maintenance and calibration services is that it helps to simplify schedules and minimize maintenance cost by avoiding repair rounds.We also keep a track record of our customers along with due date	for the necessary service and schedule the engineer visit before the deadline "
	}, {
		title: "Impurity isolation and supply",
		body: "Impurity isolation and supply During a manufacturing process or a stability study for an Active Pharmaceutical Ingredient (API) or drug product, a sample may be found to contain impurities. These impurities might occur as degradation products, as intermediates/process impurities originating from the synthetic route, as an unwanted by-product of side-reactions or due to contamination of the original sample. Such impurities can arise at very low concentrations relative to the API, perhaps as little as 0.05% w/w, but it is important that when discovered they are isolated and identified. The ICH Q3 guidelines for Impurities in New Drug Substances (Q3A(R2)) and for Impurities in New Drug Products (Q3B(R2)) clearly state that degradation products observed during manufacturing and stability studies, conducted at the recommended storage conditions, should be identified when present at a level greater than the identification thresholds."
	}, {
		title: "Analytical Method development & validation",
		body: "Analytical Method development & validation Analytical methods development and validation play important roles in the discovery, development and Manufacture of pharmaceuticals. Method development is the process of proving that an analytical method is acceptable for use to measure the concentration of an API in a specific compounded dosage form which allow simplified procedures to be employed to verify that an analysis procedure, accurately and consistently will deliver a reliable measurement of an active ingredient in a compounded preparation. The analytical method validation is essential for analytical method development and tested extensively for specificity, linearity, accuracy, precision, range, detection limit, quantization limit, and robustness. In summary, analytical method development and validation allows to confirm that an accurate and reliable potency measurement of a pharmaceutical preparation can be performed. "
	}
]


function openPop(num){
	$('#title').html(services[num].title);
	$('#body').html(services[num].body);
	$('.cst-pop').fadeIn();
}
$('.cls').click(function(){
		$('.cst-pop').fadeOut();
})